# This is a basic workflow to help you get started with Actions

name: ORT

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ort-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: data-dir
        key: data
    - name: Analyze licensing
      id: ort-action
      uses: joshmue/ort-action-container@main
      with:
        script: |
          ort analyze -i . -o $PWD/result
          ort evaluate -i $PWD/result/analyzer-result.yml -o $PWD/result --rules-file test.rules.kts
    - name: result-upload
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: result

